well_known_ports = {
    20: "FTP (File Transfer Protocol) - Data Transfer",
    21: "FTP (File Transfer Protocol) - Command Control",
    22: "SSH (Secure Shell) - Secure Login",
    23: "Telnet - Unencrypted text communications",
    25: "SMTP (Simple Mail Transfer Protocol) - Email Routing",
    53: "DNS (Domain Name System)",
    67: "DHCP (Dynamic Host Configuration Protocol) - Server",
    68: "DHCP (Dynamic Host Configuration Protocol) - Client",
    69: "TFTP (Trivial File Transfer Protocol)",
    80: "HTTP (Hypertext Transfer Protocol) - Standard web traffic",
    110: "POP3 (Post Office Protocol version 3) - Email retrieval",
    119: "NNTP (Network News Transfer Protocol) - Usenet news",
    123: "NTP (Network Time Protocol) - Time syncing",
    137: "NetBIOS Name Service",
    138: "NetBIOS Datagram Service",
    139: "NetBIOS Session Service",
    143: "IMAP (Internet Message Access Protocol) - Email retrieval",
    161: "SNMP (Simple Network Management Protocol)",
    162: "SNMP Trap",
    179: "BGP (Border Gateway Protocol)",
    201: "AppleTalk Routing Maintenance",
    389: "LDAP (Lightweight Directory Access Protocol)",
    443: "HTTPS (HTTP Secure) - Secure web traffic",
    445: "SMB (Server Message Block) - Windows file sharing",
    465: "SMTPS (Secure SMTP) - Email Routing (SSL/TLS)",
    500: "IKE (Internet Key Exchange) - VPN",
    514: "Syslog - Logging",
    520: "RIP (Routing Information Protocol)",
    587: "SMTP (Email) alternate",
    631: "IPP (Internet Printing Protocol)",
    993: "IMAPS (Secure IMAP) - Email retrieval (SSL/TLS)",
    995: "POP3S (Secure POP3) - Email retrieval (SSL/TLS)",
    1025: "Microsoft RPC",
    1080: "SOCKS Proxy",
    1194: "OpenVPN",
    1433: "Microsoft SQL Server",
    1434: "Microsoft SQL Monitor",
    1521: "Oracle SQL",
    1701: "L2TP (Layer 2 Tunneling Protocol)",
    1723: "PPTP (Point-to-Point Tunneling Protocol) - VPN",
    2049: "NFS (Network File System)",
    2082: "cPanel default",
    2083: "cPanel over SSL",
    2086: "WHM (Web Host Manager) default",
    2087: "WHM (Web Host Manager) over SSL",
    2095: "cPanel webmail",
    2096: "cPanel webmail over SSL",
    3306: "MySQL Database Service",
    3389: "RDP (Remote Desktop Protocol) - Windows remote desktop",
    5060: "SIP (Session Initiation Protocol) - VoIP signaling",
    5432: "PostgreSQL Database Service",
    5900: "VNC (Virtual Network Computing) - Remote desktop",
    5984: "CouchDB",
    6379: "Redis",
    8080: "HTTP Alternate (http-alt) - Web traffic",
    8443: "HTTPS Alternate (pcsync-https) - SSL",
    27017: "MongoDB Database Service",
    28017: "MongoDB Web Status Page",
}
